# Generated by Django 5.2.5 on 2025-08-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('personnel_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='ScoringStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('deduction_points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scoring_standard',
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announcement_number', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_announcement',
            },
        ),
        migrations.CreateModel(
            name='VehicleDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('activation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_device',
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announcement_number', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.group')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnel')),
            ],
            options={
                'db_table': 'group_announcement',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.group')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.vehicledevice')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.trip')),
            ],
            options={
                'db_table': 'route_log',
            },
        ),
        migrations.CreateModel(
            name='AiVisionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('event_details', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.scoringstandard')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.trip')),
            ],
            options={
                'db_table': 'ai_vision_log',
            },
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_number', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.trip')),
            ],
            options={
                'db_table': 'video_record',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.group')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnel')),
            ],
            options={
                'db_table': 'group_member',
                'unique_together': {('group', 'personnel')},
            },
        ),
    ]
