# Generated by Django 5.2.5 on 2025-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
