# Generated by Django 5.2.5 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personnel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': '人員', 'verbose_name_plural': '人員管理'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('MALE', '男'), ('FEMALE', '女'), ('UNSPECIFIED', '不願透漏')], default='UNSPECIFIED', max_length=20, verbose_name='性別'),
        ),
    ]
