# Generated by Django 5.2.5 on 2025-08-28 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personnel_options_alter_personnel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='license_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='駕照號碼格式必須為：1位英文大寫字母 + 9位數字。', regex='^[A-Z]\\d{9}$')], verbose_name='駕照號碼'),
        ),
    ]
