# Generated by Django 5.2.5 on 2025-08-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_personnel_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': '人員', 'verbose_name_plural': 'personnel'},
        ),
    ]
