[versions]
agp = "8.9.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
navigation-compose = "2.9.2"
lifecycle-compose = "2.6.1"
accompanist = "0.34.0"
maps-compose = "4.3.3"
play-services-location = "21.2.0"
okhttp = "4.11.0"
kotlinxCoroutines = "1.7.3"
kotlinxSerializationJson = "1.6.0"
retrofit = "2.9.0"
kotlinxSerializationConverter = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
camerax-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version = "1.2.0-beta01" }
camerax-core = { group = "androidx.camera", name = "camera-core", version = "1.2.3" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version = "1.2.3" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version = "1.2.3" }
camerax-view = { group = "androidx.camera", name = "camera-view", version = "1.2.3" }
mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version = "17.2.0" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version = "v3.1.0" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version = "18.2.0" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-compose" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.0.4" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.8" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
# --- Retrofit & Gson (用於網路請求和 JSON 解析) ---
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
# --- Kotlin Coroutines (用於非同步任務) ---

maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "maps-compose" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
# Retrofit & OkHttp
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
#retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConverter" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


[bundles]
# 建立一個 bundle 可以讓您在 build.gradle.kts 中一次性引入，更方便
#retrofit = ["retrofit-core", "retrofit-converter-gson", "okhttp-core", "okhttp-loggingInterceptor"]
retrofit = ["retrofit-core", "retrofit-converter-kotlinx-serialization", "okhttp-core", "okhttp-loggingInterceptor"]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-android"]


