# Generated by Django 5.2.5 on 2025-08-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aivisionlog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aivisionlog_set', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='routelog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_logs', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='videorecord',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videorecord_set', to='api.trip'),
        ),
    ]
