# Generated by Django 5.2.7 on 2025-10-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_created_by_group_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='邀請碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group', verbose_name='所屬群組')),
            ],
            options={
                'verbose_name': '群組邀請碼',
                'verbose_name_plural': '12. 群組邀請碼',
            },
        ),
    ]
