# Generated by Django 5.2.7 on 2025-10-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('MEMBER', '成員'), ('ADMIN', '管理員')], default='MEMBER', max_length=10, verbose_name='群組角色'),
        ),
    ]
