# Generated by Django 5.2.7 on 2025-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_groupmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupannouncement',
            name='announcement_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
