# Generated by Django 5.2.7 on 2025-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tripsuggestionfeedback_delete_chatbotfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='in_car_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='車內評分'),
        ),
        migrations.AddField(
            model_name='trip',
            name='out_car_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='車外評分'),
        ),
    ]
