CREATE TABLE IF NOT EXISTS driving_scores (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主鍵，自動遞增',
  staff_id VARCHAR(50) NOT NULL COMMENT '駕駛編號（來自staff表）',
  event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '評分時間',
  total_score DECIMAL(5,2) DEFAULT 0 COMMENT '總分',
  PRIMARY KEY (id),
  FOREIGN KEY (staff_id) REFERENCES staff(staff_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
