# Generated by Django 5.2.5 on 2025-08-30 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '群組',
                'verbose_name_plural': '2. 群組管理',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='PersonnelProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號')),
                ('personnel_number', models.CharField(max_length=50, unique=True, verbose_name='人員編號')),
                ('gender', models.CharField(choices=[('MALE', '男'), ('FEMALE', '女'), ('UNSPECIFIED', '不願透漏')], default='UNSPECIFIED', max_length=20, verbose_name='性別')),
                ('license_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='駕照號碼格式必須為：1位英文大寫字母 + 9位數字。', regex='^[A-Z]\\d{9}$')], verbose_name='駕照號碼')),
            ],
            options={
                'verbose_name': '人員詳細資料',
                'verbose_name_plural': '1. 人員詳細資料',
                'db_table': 'personnel_profile',
            },
        ),
        migrations.CreateModel(
            name='ScoringStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('deduction_points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '評分標準',
                'verbose_name_plural': '9. 評分標準',
                'db_table': 'scoring_standard',
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announcement_number', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '系統公告',
                'verbose_name_plural': '4. 系統公告',
                'db_table': 'system_announcement',
            },
        ),
        migrations.CreateModel(
            name='VehicleDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('activation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '車機設備',
                'verbose_name_plural': '6. 車機設備管理',
                'db_table': 'vehicle_device',
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announcement_number', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '群組公告',
                'verbose_name_plural': '5. 群組公告',
                'db_table': 'group_announcement',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicledevice')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '7. 行程管理',
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'verbose_name': '路程紀錄',
                'verbose_name_plural': '8. 路程紀錄',
                'db_table': 'route_log',
            },
        ),
        migrations.CreateModel(
            name='AiVisionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('event_details', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scoringstandard')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'verbose_name': 'AI視覺事件紀錄',
                'verbose_name_plural': '10. AI視覺事件紀錄',
                'db_table': 'ai_vision_log',
            },
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_number', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'verbose_name': '影像紀錄',
                'verbose_name_plural': '11. 影像紀錄',
                'db_table': 'video_record',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '群組成員',
                'verbose_name_plural': '3. 群組成員',
                'db_table': 'group_member',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
