# Generated by Django 5.2.7 on 2025-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_aivisionlog_trip_alter_routelog_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='個人頭像'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='driving_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='駕駛年資'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='license_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='駕照等級'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_mileage',
            field=models.FloatField(blank=True, null=True, verbose_name='總里程(KM)'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='駕照號碼'),
        ),
    ]
