# Generated by Django 5.2.7 on 2025-10-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_groupannouncement_announcement_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.JSONField(verbose_name='完整對話歷史')),
                ('ai_response', models.TextField(verbose_name='AI 的回應')),
                ('feedback_type', models.IntegerField(choices=[(1, '喜歡'), (-1, '不喜歡')], verbose_name='回饋類型')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='使用者評論')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='回饋時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回饋使用者')),
            ],
            options={
                'verbose_name': 'AI客服回饋',
                'verbose_name_plural': '13. AI客服回饋',
            },
        ),
    ]
