# Generated by Django 5.2.7 on 2025-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatbotfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='nfc_card_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NFC 卡片識別碼'),
        ),
    ]
