# Generated by Django 5.2.7 on 2025-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_personnelprofile_nfc_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='影片雲端網址'),
        ),
        migrations.AlterField(
            model_name='videorecord',
            name='video_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
