# Generated by Django 5.2.7 on 2025-10-05 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_videorecord_video_url_alter_videorecord_video_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.IntegerField(choices=[(1, '有幫助'), (-1, '沒有幫助')], verbose_name='回饋類型')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='使用者評論')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='回饋時間')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip', verbose_name='關聯行程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回饋使用者')),
            ],
            options={
                'verbose_name': 'AI行程建議回饋',
                'verbose_name_plural': '13. AI行程建議回饋',
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ChatbotFeedback',
        ),
    ]
