# Generated by Django 5.2.7 on 2025-10-10 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trip_in_car_score_trip_out_car_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='啟用碼')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_activation_code', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '系統啟用碼',
                'verbose_name_plural': '14. 系統啟用碼管理',
            },
        ),
    ]
