# Generated by Django 5.2.7 on 2025-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='name',
            field=models.CharField(default='Default Invite', max_length=100, verbose_name='邀請名稱'),
        ),
    ]
