# Generated by Django 5.2.7 on 2025-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_invitationcode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='activationcode',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='activationcode',
            name='used_by',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='current_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='當前使用次數'),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=50, verbose_name='最大使用次數'),
        ),
    ]
