# Generated by Django 5.2.7 on 2025-10-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_activationcode_is_used_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteLog',
        ),
    ]
