# Generated by Django 5.2.7 on 2025-10-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_routelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
